### ISSUE TITLE
Can't set long cookies

### ISSUE THREAD

**Issue by Shonke** [browserless/chrome#660] opened 2020-03-31 12:59 UTC
Hello, I noticed that the "browserless_code" was too big, causing the cookie to fail.
How do I fix it?

Related code:
https://github.com/browserless/chrome/blob/master/debugger/index.html#L625
https://github.com/browserless/chrome/blob/master/src/puppeteer-provider.ts#L274

**Comment by joelgriffith** [comment] 2020-03-31 16:26
Thanks for the report. This is a duplicate of https://github.com/browserless/chrome/issues/360, which I'm tentatively working on a fix for. I'm going to close this so we can track there!

**Closed by joelgriffith** 2020-03-31 16:26 UTC
