### ISSUE TITLE
--user-data-dir folder is empty after execution

### ISSUE THREAD

**Issue by melalj** [browserless/chrome#468] opened 2019-12-03 16:53 UTC
I'm deploying a self-hosted browserless.
An NFS volume is mounted on `/var/nfs` (that is mounted to both browserless and the client pods).
The client connects to browserless using the following:
```js
  await fs.ensureDir('/var/nfs/sessions');
  const userDataDir = `/var/nfs/sessions/${sessionId}`;
  await fs.ensureDir(userDataDir);

  const browser = await puppeteer.connect({
    browserWSEndpoint: `${browserWSEndpoint}/?--user-data-dir=${userDataDir}&--disable-web-security`,
    ignoreHTTPSErrors: true,
    headless: true,
  });
```

After executing a few actions with the browser, I check the content of the `user-data-dir` content and it's empty...
Am I missing something?
Thanks ✌️

**Comment by joelgriffith** [comment] 2019-12-04 00:28
Thanks for the report! I’m suspect that our data-dir cleanup is happening here and it shouldn’t.

Could you dump the logs from browserless here?

**Comment by melalj** [comment] 2019-12-04 00:47
```
2019-12-04T00:30:12.101Z browserless:job O7NIU8ZQNDQC7UW4A7QPCUQN8VA5HEVI: /?--user-data-dir=/var/nfs/sessions/<redacted:SESSION_ID>&--no-sandbox&--disable-web-security&timeout=720000&--proxy-server=http%3A%2F%2F<redacted:PROXY>: Inbound WebSocket request.
2019-12-04T00:30:12.102Z browserless:job O7NIU8ZQNDQC7UW4A7QPCUQN8VA5HEVI: Adding new job to queue.
2019-12-04T00:30:12.102Z browserless:job O7NIU8ZQNDQC7UW4A7QPCUQN8VA5HEVI: Getting browser.
2019-12-04T00:30:12.102Z browserless:system Using pre-booted chrome: false
2019-12-04T00:30:12.102Z browserless:chrome-helper Launching Chrome with args: {
  "args": [
    "--no-sandbox",
    "--disable-dev-shm-usage",
    "--enable-logging",
    "--v1=1",
    "--user-data-dir=/var/nfs/sessions/<redacted:SESSION_ID>",
    "--no-sandbox",
    "--disable-web-security",
    "--proxy-server=http://<redacted:PROXY>"
  ],
  "blockAds": false,
  "headless": true,
  "ignoreDefaultArgs": false,
  "ignoreHTTPSErrors": false,
  "pauseOnConnect": false,
  "executablePath": "/usr/bin/google-chrome",
  "handleSIGINT": false,
  "handleSIGTERM": false
}
2019-12-04T00:30:12.418Z browserless:system Chrome launched 3316ms
2019-12-04T00:30:12.418Z browserless:job IRQ58HO23S2C98U6F3Y9RUZB5AMMQFNW: Starting session.
2019-12-04T00:30:12.419Z browserless:job IRQ58HO23S2C98U6F3Y9RUZB5AMMQFNW: Proxying request to /devtools/browser route: ws://127.0.0.1:43483/devtools/browser/f188bf36-148f-4013-ab94-c813c483383e.
2019-12-04T00:30:15.112Z browserless:chrome-helper Chrome PID: 18638
2019-12-04T00:30:15.513Z browserless:system Chrome launched 3411ms
2019-12-04T00:30:15.513Z browserless:job O7NIU8ZQNDQC7UW4A7QPCUQN8VA5HEVI: Starting session.
2019-12-04T00:30:15.514Z browserless:job O7NIU8ZQNDQC7UW4A7QPCUQN8VA5HEVI: Proxying request to /devtools/browser route: ws://127.0.0.1:35967/devtools/browser/5cf9e7e6-09ba-497f-a3ed-16960816f6b5.
2019-12-04T00:30:51.419Z browserless:server IRQ58HO23S2C98U6F3Y9RUZB5AMMQFNW: Recording successful stat and cleaning up.
2019-12-04T00:30:51.420Z browserless:job IRQ58HO23S2C98U6F3Y9RUZB5AMMQFNW: Cleaning up job
2019-12-04T00:30:51.420Z browserless:job IRQ58HO23S2C98U6F3Y9RUZB5AMMQFNW: Browser not needed, closing
2019-12-04T00:30:51.420Z browserless:chrome-helper Shutting down browser with close command
2019-12-04T00:30:51.421Z browserless:chrome-helper Sending SIGKILL signal to browser process 18578
2019-12-04T00:30:51.807Z browserless:job IRQ58HO23S2C98U6F3Y9RUZB5AMMQFNW: Browser cleanup complete, checking swarm.
2019-12-04T00:30:51.807Z browserless:system Chrome swarm is ok, not adding additional browsers
```

**Comment by joelgriffith** [comment] 2019-12-04 16:48
I can't seem to reproduce locally, I'm guessing that it's due to system permissions. Is `/var/nfs/sessions/` writeable by anyone? Our browserless user is pretty sandboxed down: 

```RUN groupadd -r blessuser && useradd -r -g blessuser -G audio,video blessuser \
  && mkdir -p /home/blessuser/Downloads \
  && chown -R blessuser:blessuser /home/blessuser```

**Comment by melalj** [comment] 2019-12-04 17:57
should I mount the nfs volume on `/home/blessuser`?

**Comment by joelgriffith** [comment] 2019-12-04 18:45
Yeah, I'd give that a shot since it _should_ be writeable

**Comment by melalj** [comment] 2019-12-09 10:57
I set the permission to the directory `/home/blessuser/nfs/sessions` to `777`.
Ran browserless for few days but the folders are still empty :(

**Comment by joelgriffith** [comment] 2019-12-09 22:29
OK, one last thing to check, could you perhaps start the session and _not_ close it? This way we can see if it's getting written properly out, and it's not browserless accidentally deleting the folder.

**Comment by melalj** [comment] 2019-12-10 13:31
You mean not closing the browser `browser.close()`?
I tried not closing the browser an it's still empty user-data-dir.. something might be causing this (strange that it didn't happen to other browserless users)

**Comment by joelgriffith** [comment] 2019-12-10 19:52
What's your `docker run` command look like? Since the directory isn't being made on the host device then it's likely being made in the container someplace (my guess)

**Comment by melalj** [comment] 2019-12-10 20:48
Here's the Kubernetes yaml for browserless I'm using, maybe it may help debug:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserless
  labels:
    app: browserless
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: browserless
  template:
    metadata:
      labels:
        app: browserless
    spec:
      restartPolicy: Always
      volumes:
        - name: sessions-nfs
          persistentVolumeClaim:
            claimName: nfs
      containers:
        - name: browserless
          image: browserless/chrome
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/home/blessuser/nfs"
              name: sessions-nfs
          resources:
            requests:
              cpu: "250m"
              memory: "750Mi"
            limits:
              cpu: "300m"
              memory: "1000Mi"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: CONNECTION_TIMEOUT
              value: "420000"
            - name: ENABLE_DEBUGGER
              value: "false"
            - name: MAX_CONCURRENT_SESSIONS
              value: "5"
            - name: PREBOOT_CHROME
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: browserless
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  selector:
    app: browserless
```

**Comment by joelgriffith** [comment] 2020-03-01 19:27
Looking further into this, it looks like if chrome doesn't have write access then it won't show up here. Is it possible for you to see what `/home/blessuser/nfs` permissions have?

**Closed** 2020-03-03 17:00 UTC
