### ISSUE TITLE
Cannot connect via Playwright >= 1.6.0

### ISSUE THREAD

**Issue by YusukeIwaki** [browserless/chrome#1419] opened 2021-04-18 16:06 UTC
**Describe the bug**

```
const playwright = require('playwright')

playwright.chromium.connect({
    wsEndpoint: 'wss://chrome.browserless.io/playwright?token=YOUR-TOKEN',
}).then(async (browser) => {
    const context = await browser.newContext();
    const page = await context.newPage();

    await page.goto('https://www.example.com/');
    await page.screenshot({ path: 'example.png' });

    await browser.close();
})
```

(ref: https://docs.browserless.io/docs/playwright.html)

This example code works on Playwright 1.5.0. But not working on Playwright 1.6.0 or later...

**To Reproduce**

Described above with example code.

```
$ node example.js 
/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/utils/utils.js:124
    for (const { name, value } of headers)
                                  ^

TypeError: headers is not iterable
    at Object.headersArrayToObject (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/utils/utils.js:124:35)
    at new Response (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/network.js:185:42)
    at Connection._createRemoteObject (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/connection.js:208:26)
    at Connection.dispatch (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/connection.js:105:18)
    at Immediate.<anonymous> (/Users/yusuke-iwaki/Desktop/pl-test/node_modules/playwright/lib/client/browserType.js:112:50)
    at processImmediate (internal/timers.js:461:21)
```

**Expected behavior**

works well

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by YusukeIwaki** [comment] 2021-04-18 16:09
`playwright.chromium.connectOverCDP` is available on Playwright >= 1.9.0
It seems we can use it just like `puppeteer.connect`.

**Comment by joelgriffith** [comment] 2021-04-21 17:43
Looks like this is only on the version of Chrome we have in our usage-based cluster. We'll work on updating that which should fix this issue. In the meantime I'll look to add `playwright.chromium.connectOverCDP` to our documentation.

**Comment by joelgriffith** [comment] 2021-05-18 02:26
Closing this since there are a few workarounds and the issue is only with a certain hosted product

**Closed by joelgriffith** 2021-05-18 02:26 UTC
