### ISSUE TITLE
Could you pls offer browserless image for apple mac m1

### ISSUE THREAD

**Issue by shmilyoo** [browserless/chrome#1393] opened 2021-04-02 04:15 UTC
Could you pls offer browserless image for apple mac m1,
I build the image, but failed.

**Comment by joelgriffith** [comment] 2021-04-05 18:55
Afraid I don't have an M1 Mac to assist. Could you paste some more logs/info than what you've got?

**Comment by shmilyoo** [comment] 2021-04-06 02:17
After replacing it with a mac m1 laptop, my chrome is not working properly

```
pdf-service-chrome | 2021-04-06T02:14:04.053Z browserless:system TimeoutError: waiting for target failed: timeout 30000ms exceeded
pdf-service-chrome |     at Object.waitWithTimeout (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/helper.js:224:26)
pdf-service-chrome |     at Browser.waitForTarget (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:269:45)
pdf-service-chrome |     at ChromeLauncher.launch (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:100:27)
pdf-service-chrome |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
pdf-service-chrome |     at async Object.exports.launchChrome (/usr/src/app/build/chrome-helper.js:278:13)
pdf-service-chrome |     at async Promise.all (index 0)
pdf-service-chrome |     at async BrowserlessServer.startServer (/usr/src/app/build/browserless.js:166:9) Issue launching Chrome, retrying 1 times.
```

version: 1.43.0-puppeteer-5.4.1

**Comment by joelgriffith** [comment] 2021-04-24 18:58
I'm assuming you've tried `--platform linux/amd64` ?

**Comment by dmrty** [comment] 2021-04-25 12:56
Same problem here. Unfortunately that's not that easy.

I have the same issue. Upon further investigation, I found in the `chrome_debug.log` (under `/tmp/browserless-data-dir-2Yf3f0/Default`, the id of the data dir changing) the following content : 
```
[0425/121322.935410:ERROR:file_path_watcher_linux.cc(318)] inotify_init() failed: Function not implemented (38)
[0425/121323.080666:WARNING:gpu_process_host.cc(1204)] The GPU process has crashed 1 time(s)
[0425/121323.094925:WARNING:gpu_process_host.cc(1204)] The GPU process has crashed 2 time(s)
[0425/121323.101529:WARNING:gpu_process_host.cc(1204)] The GPU process has crashed 3 time(s)
[0425/121323.108848:WARNING:gpu_process_host.cc(1204)] The GPU process has crashed 4 time(s)
[0425/121323.115357:WARNING:gpu_process_host.cc(1204)] The GPU process has crashed 5 time(s)
[0425/121323.122162:WARNING:gpu_process_host.cc(1204)] The GPU process has crashed 6 time(s)
[0425/121323.136177:WARNING:gpu_process_host.cc(1204)] The GPU process has crashed 7 time(s)
[0425/121323.225126:WARNING:gpu_process_host.cc(1204)] The GPU process has crashed 8 time(s)
[0425/121323.288251:WARNING:gpu_process_host.cc(1204)] The GPU process has crashed 9 time(s)
[0425/121323.288428:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
```

The first line `inotify_init() failed` seem to refer to `iNotify` not being compatible with Docker for Mac with M1, see 
https://docs.docker.com/docker-for-mac/apple-silicon/ : 
> Filesystem change notification APIs (e.g. inotify) do not work under QEMU emulation, see docker/for-mac#5321.

Also I'm passing `--disable-gpu` to the container without any luck :-( 
```
chrome_1     | 2021-04-25T12:53:10.555Z browserless:system TimeoutError: waiting for target failed: timeout 30000ms exceeded
chrome_1     |     at Function.waitWithTimeout (/usr/src/app/node_modules/puppeteer/lib/helper.js:214:26)
chrome_1     |     at Browser.waitForTarget (/usr/src/app/node_modules/puppeteer/lib/Browser.js:214:27)
chrome_1     |     at Browser.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:111:23)
chrome_1     |     at Launcher.launch (/usr/src/app/node_modules/puppeteer/lib/Launcher.js:178:21)
chrome_1     |     at processTicksAndRejections (internal/process/task_queues.js:97:5) Issue launching Chrome, retrying 1 times.
chrome_1     | 2021-04-25T12:53:10.560Z browserless:chrome-helper Launching Chrome with args: {
chrome_1     |   "args": [
chrome_1     |     "--no-sandbox",
chrome_1     |     "--enable-logging",
chrome_1     |     "--v1=1",
chrome_1     |     "--disable-gpu",
chrome_1     |     "--remote-debugging-port=45295",
chrome_1     |     "--user-data-dir=/tmp/browserless-data-dir-nrgpzd",
chrome_1     |     "--remote-debugging-pipe"
chrome_1     |   ],
chrome_1     |   "blockAds": false,
chrome_1     |   "headless": true,
chrome_1     |   "ignoreDefaultArgs": false,
chrome_1     |   "ignoreHTTPSErrors": false,
chrome_1     |   "pauseOnConnect": false,
chrome_1     |   "executablePath": "/usr/bin/google-chrome",
chrome_1     |   "handleSIGINT": false,
chrome_1     |   "handleSIGTERM": false
```

**Comment by joelgriffith** [comment] 2021-05-17 19:39
Appears to be due to the fact that Chrome uses some file-system listeners that docker doesn't yet support. Would love to offer this, but can't just yet at this time :/

**Comment by vovimayhem** [comment] 2021-08-28 17:21
> We do have a chrome stable release… might be worth trying `1-chrome-stable` Tag?

That turned out to be another `linux/amd64` image... I'm attempting to build a `linux/arm64` image instead :/

So far, haven't found a precompiled version of Chrome for `linux/arm64` - looks like the Chrome team has yet to release one at all.

Is there any inconvenience on using Chromium instead of Chrome? That way, I could at least try to build a `linux/arm64` version...

**Comment by vovimayhem** [comment] 2021-08-28 21:28
OH MY I had no idea building Chromium would be a daunting task...

**Comment by mpietrucha** [comment] 2021-09-16 19:46
Any updates here?

**Comment by XBeg9** [comment] 2021-09-17 13:57
same here, has someone tried to build their own arm64 image? I have no luck running this on raspbian arm64

**Comment by broofa** [comment] 2021-09-18 16:49
Haven't solved this yet, but here's where I'm at with trying to build for M1:
* Following [these instructions](https://jitsu.com/blog/multi-platform-docker-builds) for doing M1 builds
* Modified `Dockerfile` thusly (to work around various other issues):
```diff
$ git diff -U0 Dockerfile
diff --git a/Dockerfile b/Dockerfile
index e7f3822..685c0ac 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1 +1 @@
-FROM browserless/base:1.12.0
+FROM node:16
@@ -18 +17,0 @@ ENV PUPPETEER_CHROMIUM_REVISION=${PUPPETEER_CHROMIUM_REVISION}
-ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
@@ -39,9 +38,4 @@ RUN if [ "$USE_CHROME_STABLE" = "true" ]; then \
-RUN if [ "$USE_CHROME_STABLE" = "true" ]; then \
-    export CHROMEDRIVER_SKIP_DOWNLOAD=false;\
-  else \
-    export CHROMEDRIVER_SKIP_DOWNLOAD=true;\
-  fi &&\
-  npm i puppeteer@$PUPPETEER_VERSION;\
-  npm run postinstall &&\
-  npm run build &&\
-  chown -R blessuser:blessuser $APP_DIR
+RUN npm i puppeteer@$PUPPETEER_VERSION
+RUN npm run postinstall
+RUN npm run build
+RUN chown -R blessuser:blessuser $APP_DIR
```
* Running this build command: `docker buildx build --platform linux/arm64 -t browserless/chrome .`

The build errors out inside `npm i puppeteer@$PUPPETEER_VERSION` with [this error](https://github.com/puppeteer/puppeteer/issues/6622):

```
#12 13.46 npm ERR! /usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:115
#12 13.46 npm ERR!                     throw new Error();```
```

It looks like recent versions of `puppeteer` will [look for `/usr/bin/chromium`](https://github.com/puppeteer/puppeteer/blob/main/src/node/BrowserFetcher.ts#L113-L121), but I'm unsure how to get an `linux/arm64` build of `chromium` installed using Dockerfile (from `node:16` base image). 

Any suggestions?

**Comment by XBeg9** [comment] 2021-09-20 15:59
I was able to run this on my raspberry setup, can someone try this image? `docker run -p 3000:3000 -it skitsko/browserless:arm7` and then go to :3000

**Comment by mpietrucha** [comment] 2021-09-20 16:17
<img width="1680" alt="Zrzut ekranu 2021-09-20 o 18 16 58" src="https://user-images.githubusercontent.com/25660996/134037225-ffadb26a-9fc5-4b3d-a8c3-b1ba582d7d7c.png">

@XBeg9 

Seems to be working in apple silicon m1, but can't connect through websockets

**Comment by XBeg9** [comment] 2021-09-20 16:19
I was able to test all 4 demos on raspberry, could you please bring network tab with errors here?

**Comment by mpietrucha** [comment] 2021-09-20 16:25
Demos working, what i mean by connect through websockets is connect to webdriver on port 9222

**Comment by XBeg9** [comment] 2021-09-20 16:27
have you exposed 9222 to your host machine? :)

**Comment by mpietrucha** [comment] 2021-09-20 16:33
Ok, my mistake. You've made great job! Everything is working like charm

**Comment by joelgriffith** [comment] 2021-09-23 22:21
Following up: seems like some good progress -- anyone want to do a PR? Happy to help facilitate one or help where I can. Sadly I have no m1 to test on :/

**Comment by XBeg9** [comment] 2021-10-04 16:17
@joelgriffith sorry, I had a vacation, going to do PR probably next few days...

**Comment by tomasc** [comment] 2021-11-04 14:02
Hi @SebastianBar, thank for the PR!

I built an image off of your [branch](https://github.com/SebastianBar/chrome/tree/armv8-build), using `docker buildx build --platform linux/amd64,linux/arm64 -t tomasce/chrome:latest --push ./base`. (It is now available at https://hub.docker.com/repository/docker/tomasce/chrome)

Yet when trying to run it `docker run --rm -p 3000:3000 -e "MAX_CONCURRENT_SESSIONS=10" tomasce/chrome:latest` fails (the command just immediately exits out without any error message). (I am on Apple M1 Pro.)

Can you please advice how to get this working?

Thanks! 
Tomas

**Comment by XBeg9** [comment] 2021-11-04 14:09
@SebastianBar @tomasc 

I am really sorry posting this here instead of creating the PR

```Dockerfile
FROM arm64v8/ubuntu:18.04 as base

ARG BLESS_USER_ID=999

COPY base/fonts.conf /etc/fonts/local.conf

# Dependencies + NodeJS
RUN apt-get -qq update && \
  echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections && \
  apt-get -y -qq install software-properties-common &&\
  apt-add-repository "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner" && \
  apt-get -qq update && apt-get -y -qq --no-install-recommends install \
  dumb-init \
  # adobe-flashplugin \
  git \
  ffmpeg \
  fonts-liberation \
  msttcorefonts \
  fonts-roboto \
  fonts-ubuntu \
  fonts-noto-color-emoji \
  fonts-noto-cjk \
  fonts-ipafont-gothic \
  fonts-wqy-zenhei \
  fonts-kacst \
  fonts-freefont-ttf \
  fonts-thai-tlwg \
  fonts-indic \
  fontconfig \
  libappindicator3-1 \
  # pdftk \
  unzip \
  locales \
  gconf-service \
  libasound2 \
  libatk1.0-0 \
  libc6 \
  libcairo2 \
  libcups2 \
  libdbus-1-3 \
  libexpat1 \
  libfontconfig1 \
  libgcc1 \
  libgconf-2-4 \
  libgdk-pixbuf2.0-0 \
  libglib2.0-0 \
  libgtk-3-0 \
  libnspr4 \
  libpango-1.0-0 \
  libpangocairo-1.0-0 \
  libstdc++6 \
  libx11-6 \
  libx11-xcb1 \
  libxcb1 \
  libxcomposite1 \
  libxcursor1 \
  libxdamage1 \
  libxext6 \
  libxfixes3 \
  libxi6 \
  libxrandr2 \
  libxrender1 \
  libxss1 \
  libxtst6 \
  libllvm8 \
  libgbm-dev \
  ca-certificates \
  libappindicator1 \
  libnss3 \
  lsb-release \
  xdg-utils \
  wget \
  xvfb \
  curl &&\
  curl --silent --location https://deb.nodesource.com/setup_16.x | bash - &&\
  apt-get -y -qq install nodejs &&\
  apt-get -y -qq install build-essential

# Add the browserless user (blessuser)
RUN groupadd -r blessuser && useradd --uid ${BLESS_USER_ID} -r -g blessuser -G audio,video blessuser \
  && mkdir -p /home/blessuser/Downloads \
  && chown -R blessuser:blessuser /home/blessuser

# Install deps necessary to build
RUN npm install -g typescript @types/node

# Install Chrome Stable
ENV CHROME_BINARY_LOCATION /usr/bin/google-chrome
RUN apt-get -y install chromium-browser && \
  ln -s /usr/bin/chromium-browser ${CHROME_BINARY_LOCATION}

# Install Chrome driver
ENV CHROMEDRIVERVERSION=14.0.1
ENV ARCH=arm64
RUN wget -q https://github.com/electron/electron/releases/download/v$CHROMEDRIVERVERSION/chromedriver-v$CHROMEDRIVERVERSION-linux-$ARCH.zip -O /tmp/driver.zip && \ 
  unzip /tmp/driver.zip -d /tmp/ && \
  mv -f /tmp/chromedriver /usr/bin/ && \
  chmod +x /usr/bin/chromedriver

# Install libvips
ENV LIBVIPSVERSION=8.11.3
RUN apt-get install -y -qq --no-install-recommends glib2.0-dev libexpat1-dev && \
  wget -q https://github.com/libvips/libvips/releases/download/v${LIBVIPSVERSION}/vips-${LIBVIPSVERSION}.tar.gz -O /tmp/vips-${LIBVIPSVERSION}.tar.gz && \
  cd /tmp && tar xf vips-${LIBVIPSVERSION}.tar.gz && cd vips-${LIBVIPSVERSION} && \
  ./configure && \
  make && make install && ldconfig

RUN fc-cache -f -v &&\
  apt-get -qq clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

###########################################################

FROM base

# Application parameters and variables
ENV APP_DIR=/usr/src/app
ENV CONNECTION_TIMEOUT=60000
ENV ENABLE_XVBF=true
ENV HOST=0.0.0.0
ENV IS_DOCKER=true
ENV NODE_ENV=production
ENV PORT=3000
ENV WORKSPACE_DIR=$APP_DIR/workspace

ENV USE_CHROME_STABLE=true
ENV CHROMEDRIVER_SKIP_DOWNLOAD=true
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

RUN mkdir -p $APP_DIR $WORKSPACE_DIR

WORKDIR $APP_DIR

# Install app dependencies
COPY package.json .
COPY tsconfig.json .
COPY . .

# Build
RUN npm install --arch=arm64 --platform=linux --ignore-scripts && \
  npm run build && \
  chown -R blessuser:blessuser $APP_DIR

# Run everything after as non-privileged user.
USER blessuser

# Expose the web-socket and HTTP ports
EXPOSE 3000
ENTRYPOINT ["dumb-init", "--"]
CMD [ "node", "./build/index.js" ]
```

I think there must be GitHub action pipeline + multiarch build job done before merging the PR, that's exact Dockerfile that I have used to run the docker on raspi (arm64), feel free to create the PR using it, I have a limited time right now and can't really help with the PR :(

**Comment by tomasc** [comment] 2021-11-04 14:10
@SebastianBar thanks a lot for such a quick response – I will give it a go!

**Comment by tomasc** [comment] 2021-11-04 14:11
I mean: Thanks @XBeg9 ;-))))

**Comment by XBeg9** [comment] 2021-11-04 14:13
@tomasc np, sorry for really late response.

P.S. My image could dramatically change build post-install scripts, my plan was to run the image asap and not to cover all possible solutions, I am open for communication here or inside @SebastianBar PR, btw it looks really good.

**Comment by tomasc** [comment] 2021-11-04 14:14
@XBeg9 just to clairfy – these Dockerfiles are meant to be added on top of master or @SebastianBar's PR?

**Comment by tomasc** [comment] 2021-11-04 14:18
@XBeg9 got it, will give it a try, thanks!

**Comment by tomasc** [comment] 2021-11-08 07:57
@XBeg9 I ended up using your image locally, works fine, thank you!
It would be good to look into how to make your Dockerfile support both architectures, or finish up on @SebastianBar's PR (I haven't managed to build it locally yet). 
I will try to find some time for it, but perhaps someone else will be faster. Let's see.

**Comment by SebastianBar** [comment] 2021-11-08 14:17
If you have an up-to-date Docker, I think you could run a build by manually reverting to this (that's how I worked with it on my local env):
https://github.com/browserless/chrome/pull/1847/commits/627325284e10ba9a449af38f5b0ff9daef2a3117

Then you can run a regular `docker build ....` on the base path of the repo, and all should be good to go.
If helpful to test, I could build a couple pipelines to deploy my branch into Dockerhub.

**Comment by SebastianBar** [comment] 2021-11-08 22:33
Ok, so I noticed that my branch is able to be built on M1, but using docker build,
- If I try to build on ARM64 for ARM64 and AMD64, AMD64 fails
- If I try to build on AMD64 for ARM64 and AMD64, ARM64 fails

 So I guess the issue is over QEMU not being able to get Chrome/Chromium up and running (required only by one of the postinstall scripts). I'll try to see if I can do something, but seems pretty rough.

**Comment by SebastianBar** [comment] 2021-11-08 23:08
Ok, so, I've run the build process twice (once in the M1, another on an Intel Macbook)
```
On amd64:
> docker build -t barrenechea/browserless:amd64 . --build-arg PUPPETEER_VERSION=11.0.0
> docker push barrenechea/browserless:amd64

On arm64:
> docker build -t barrenechea/browserless:arm64 . --build-arg PUPPETEER_VERSION=11.0.0
> docker push barrenechea/browserless:arm64
```

Then, after reading [this](https://sean.dev/2019/02/creating-multi-arch-docker-images/), I created a custom manifest to bundle both `arm64` and `amd64` tags into a single `latest`.
```
> docker manifest create docker.io/barrenechea/browserless:latest docker.io/barrenechea/browserless:arm64 docker.io/barrenechea/browserless:amd64
> docker manifest push docker.io/barrenechea/browserless:latest
```

So you can try `barrenechea/browserless:latest` and should work fine on both archs!

Still, the `get-meta.js` script should be handled without Puppeteer if we want this to work with pipelines. Or having some native arm64-based worker for the main pipelines 😆... Maybe it could run as a first-boot kind of thing? That should sort the issue.

**Comment by SebastianBar** [comment] 2021-11-09 00:30
@joelgriffith I just tried this approach:
Update start.sh, add on line 15:

```
# Check if version.json, protocol.json, hints.json and hosts.json are present. If not, get them.
if [ ! -f ./version.json ] || [ ! -f ./protocol.json ] || [ ! -f ./hints.json ] || [ ! -f ./hosts.json ]; then
  node ./scripts/get-meta.js
fi
```

And update package.json's postinstall script, with:
`"postinstall": "npm run external && npm run symlink-chrome",` // Removing npm run meta

With that, I'm able to run the full build process through QEMU (but it creates the files on every boot). Thoughts? 🤔

**Comment by tomasc** [comment] 2021-11-23 15:49
@SebastianBar I tested `barrenechea/browserless:latest` and it works well!

**Comment by joelgriffith** [comment] 2021-11-24 19:48
I've got a test tag pushed on latest, anyone willing to give it a shot?

```sh
docker pull --platform linux/arm64 browserless/chrome:latest
```

**Comment by tomasc** [comment] 2021-11-24 22:02
Thanks @joelgriffith , I will give it a try tomorrow and report back. 

BTW would it be possible to have multiplatform build — arm64 & amd64? That way I could test both on my Mac M1 (arm64) as well as in CI pipeline (amd64).

**Comment by tomasc** [comment] 2021-11-25 15:12
@joelgriffith I only see amd64 build at Docker Hub now :(
https://hub.docker.com/r/browserless/chrome/tags

**Comment by frontendr** [comment] 2021-11-25 15:51
@joelgriffith Sorry, it looks like `browserless/chrome:latest` is in some sort of a boot loop. Anything I can provide to help you out?

**Comment by joelgriffith** [comment] 2021-11-27 17:17
Will take a look soon — arm64 had to be downgraded due to the fact that it was breaking a few folks who were using `latest` in production. Multi platform build should be out Monday

**Comment by joelgriffith** [comment] 2021-11-30 03:38
OK folks, going to hopefully close this out soon. Right now we have an arm64 build: `browserless/chrome:arm64` -- in our next production release we'll create arm64-specific builds as their own tags. This is for numerous reasons, but they'll be available as `browserless/chrome:1-arm64` going forward.

**Comment by HookyQR** [comment] 2021-11-30 05:38
@joelgriffith How do you propose we handle situations where we have devs and CI on different architectures when our docker-compose contains:
```yaml
  chrome:
    image: browserless/chrome:latest # currently using barrenechea/browserless:latest
```
What's the problem with the multi-arch build? `barrenechea/browserless:latest` works great, but I would expect a multi-arch build to be maintained here. More detail on the ***numerous reasons*** please.

**Comment by joelgriffith** [comment] 2021-11-30 17:26
So we're going to build two image tag types going forward. Every time `master` is merged in this repo, we'll have a github action that builds out a `latest` tag for both amd64 and arm64. As well, we'll also build production tags of the arm64 version, with the format of: `1-arm64`, `1.1-arm64` and `1.1.1-arm64` similar to our production tags we already have. Unfortunately, do to how arm64 is supported, it's not a 1:1 ratio with how amd64 is built. Heres' the reasons why:

- We tie our production and other tags to the puppeteer version of chromium. arm64 uses playwright to download an arm64 compatible binary which isn't the same as puppeteer's chromium (generally a few versions ahead). Because of this, there isn't a strong guarantee that everything will work _exactly_ the same as it does in amd64 due to this binary difference.
- Since we do separate builds for most of the major puppeteer versions, this difference only increases as the chrome version expands. The difference between puppeteer 12.x.x and the arm64 binary is small, however the difference between puppeteer 3.x.x and the arm64 binary is quite huge (possibly years of deltas between the two). Thus, we cannot make an arm64 version of `1-puppeteer-3.4.1` because they'll operate so differently.
- Because of the difference in chrome binaries, there's also a small difference in certain APIs as well. Most of these aren't going to effect the big libraries, but certain protocol APIs (like /json/version and /json/protocol) are going to return different results depending on the platform.
- Finally, things like chromedriver might not work as well since the platforms are different. 

I think having `latest` tagged for both platforms, and a distinct `*-arm64` release tag is about as close to 1:1 as we can get, but still distinguish that there's going to be differences.

**Closed** 2021-11-30 18:30 UTC

**Comment by HookyQR** [comment] 2021-12-01 00:28
Hey @joelgriffith thanks for the details. Makes sense. With both having a `latest` tag, we should be sweet. 👍

**Comment by j-mendez** [comment] 2022-03-27 17:16
Looking into setting up a multi arch image instead of separating the builds. I want to test out this project without having to manage a separate multi staged image on top. @joelgriffith Is there a reason that the builds are split instead of multi arch?

**Comment by html5maker** [comment] 2022-05-10 09:04
Is there any way to use the GPU on M1 inside a docker container (usable for the video screencast recording)?
