### ISSUE TITLE
Playwright support broken as of v1.4.0

### ISSUE THREAD

**Issue by Niek** [browserless/chrome#1016] opened 2020-10-05 10:37 UTC
**Describe the bug**
Playwright support worked fine until version v1.4.0. That version introduced a new wire protocol, see https://github.com/microsoft/playwright/releases/tag/v1.4.0

**To Reproduce**
Install latest playwright (v1.4.2 as of writing). Connecting won't work, however when downgrading to v1.3.0 things work fine.

**Comment by berstend** [comment] 2020-10-05 11:07
The following will hang at `.connect` since `v1.4.0`:

```js
const pw = require('playwright');

(async () => {
  const browser = await pw.chromium.connect({
   wsEndpoint: 'wss://chrome.browserless.io?token=YOUR-API-TOKEN',
  });
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.goto('https://www.example.com/');
  await page.screenshot({ path: 'example.png' });

  await browser.close();
})();
```

Note that the official example uses `browserWSEndpoint`, which should be `wsEndpoint` with playwright. :)

**Comment by joelgriffith** [comment] 2020-10-05 23:33
Thanks for this, will take a look and see what's going on behind the scenes. We're working on migrating to playwright internally, but it might take some time :)

**Comment by joelgriffith** [comment] 2020-10-06 02:33
This is fairly unfortunate, as playwright has gone away from chromes embedded protocol over to their own proprietary one. This forces browserless to do one of two potential things to fix this:

- Start it’s own websocket server to sniff out whether or not the initiating message is CDP-based or not, and either start just chromium or playwrights server-side component. Possible chance of regressions because of this.

- Add some arbitrary flag to the connect call to specify its playwright initiating the connection. This would be a quicker fix, but not as robust as the above solution.

In either case both would require a bit of work to do so. I’m not sure why the breaking change on their library, as it doesn’t seem to buy much in my opinion. The transport layer is the same, and CDP already allows for cross-language/runtime compatibility.

**Comment by berstend** [comment] 2020-10-06 08:16
I agree, this is a massive breaking change that's not even documented (the API docs for `connect` don't mention it).

**Comment by Niek** [comment] 2020-10-06 08:18
Related Playwright issue: https://github.com/microsoft/playwright/issues/4054

**Comment by joelgriffith** [comment] 2020-10-06 19:30
Should be fixed in https://github.com/browserless/chrome/pull/1018

**Comment by joelgriffith** [comment] 2020-10-13 03:08
Fix is now everywhere in our platform. Closing

**Closed by joelgriffith** 2020-10-13 03:08 UTC
